services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    command: sh /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: sh /app/celery_entrypoint.sh
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data: